### ISSUE TITLE
Can't click on things

### ISSUE THREAD

**Issue by JinayJain** [veggiedefender/veggiedefender.github.io#1]
Excuse me but your website seems to be flawed as I cannot click anything and would like to contact you to make some

## awesome software.

**Comment by veggiedefender** [comment]
Those aren't links but now that I look at them they totally look like links.

I'll probably make them links then.

**Comment by JinayJain** [comment]
Thank for the _speedy_ reply m8

**Comment by veggiedefender** [comment]
lol dude find someone else to creep on

**Comment by veggiedefender** [comment]
fixed in https://github.com/veggiedefender/veggiedefender.github.io/commit/0c4a9357ee12415f8add1be29c0862a06a525c50
